#pragma once

#include <html/dom.h>

struct __HTML
{
    struct __HTML_TagNames
    {
        DOMString address;
        DOMString applet;
        DOMString area;
        DOMString article;
        DOMString aside;
        DOMString base;
        DOMString basefont;
        DOMString bgsound;
        DOMString blockquote;
        DOMString body;
        DOMString br;
        DOMString button;
        DOMString caption;
        DOMString center;
        DOMString col;
        DOMString colgroup;
        DOMString dd;
        DOMString details;
        DOMString dialog;
        DOMString dir;
        DOMString div;
        DOMString dl;
        DOMString dt;
        DOMString embed;
        DOMString fieldset;
        DOMString figcaption;
        DOMString figure;
        DOMString footer;
        DOMString form;
        DOMString frame;
        DOMString frameset;
        DOMString h1;
        DOMString h2;
        DOMString h3;
        DOMString h4;
        DOMString h5;
        DOMString h6;
        DOMString head;
        DOMString header;
        DOMString hgroup;
        DOMString hr;
        DOMString html;
        DOMString keygen;
        DOMString iframe;
        DOMString image;
        DOMString img;
        DOMString input;
        DOMString li;
        DOMString listing;
        DOMString link;
        DOMString main;
        DOMString marquee;
        DOMString menu;
        DOMString meta;
        DOMString nav;
        DOMString noembed;
        DOMString noframes;
        DOMString noscript;
        DOMString object;
        DOMString ol;
        DOMString optgroup;
        DOMString option;
        DOMString p;
        DOMString param;
        DOMString plaintext;
        DOMString pre;
        DOMString rb;
        DOMString rp;
        DOMString rt;
        DOMString rtc;
        DOMString script;
        DOMString search;
        DOMString section;
        DOMString select;
        DOMString source;
        DOMString style;
        DOMString summary;
        DOMString table;
        DOMString tbody;
        DOMString td;
        DOMString template;
        DOMString textarea;
        DOMString tfoot;
        DOMString th;
        DOMString thead;
        DOMString title;
        DOMString tr;
        DOMString track;
        DOMString ul;
        DOMString wbr;
        DOMString xmp;
    } TagNames;

    DOMString SpecialTagNames[83];
};

extern struct __HTML HTML;
